---
title: "UAW-GM: IPS"
subtitle: "Population Characteristics"
output: word_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = F)

library(here); library(boxr); box_auth(); library(tidyverse)
library(tikzDevice); library(xtable); library(pander)
panderOptions('table.split.table', 500)

# Pick variable to use for year of employment end
# yout.which <- "year_left_work"
yout.which <- "YOUT16"

# Load analytic data based on which variable used as year of employment end
dta_ips <- box_read(ifelse(yout.which == "YOUT16", 657149129798, 656285655983))
cohort_long <- box_read(488427532080) # the long dataset
	# box_read(ifelse(yout.which == "YOUT16", 657147487614, 656275470844))
dta_end_of_employment <- box_read(656270359800) # Job history

# Merge end of employment
cohort_long <- full_join(
  (if (yout.which == "YOUT16") {cohort_long %>% select(-all_of(yout.which))} else {cohort_long}),
  (dta_end_of_employment[,c("STUDYNO", yout.which)] %>% distinct),
  by = "STUDYNO")
cohort_long$filler <- 0

# Helper function to format dates
gm.to.date <- function(x) {
	x <- x + 1900
	as.Date(paste0(floor(x), '/01/01')) +
		floor((x - floor(x)) * time_length(difftime(
			as.Date(paste0(floor(x), "-12-31")),
			as.Date(paste0(floor(x), "-01-01"))), 'day'
		))}
```

```{r pop_char, include=F}
# Helper function for table
get.tab1 <- function(
	df = filter(dta_ips, filler == 0),
	table_engine = "xtable",
	use_finrace = T,
	start_year = -Inf,
	col.name = "stat") {
	
	require(data.table); require(lubridate)
	
	df <- as.data.table(as.data.frame(df))
	
	setorder(df, STUDYNO, cal_obs)
	
	# Individual-level summary
	tab1.sum <- df[,.(
		
		'\\textbf{Race}, $n$ (\\%)' = NA,
		'\\hspace{10pt}White' = if (use_finrace) {
			ifelse(FINRACE[1] == 1, 1, 0)} else {
				ifelse(FINRACE[1] == 1 | FINRACE[1] == 9, 1, 0)
			},
		'\\hspace{10pt}Black' = ifelse(FINRACE[1] == 2, 1, 0),
		'\\hspace{10pt}Unknown' = if (use_finrace) {ifelse(FINRACE[1] == 9 | FINRACE[1] == 0, 1, 0)},
		'\\textbf{Sex}, $n$ (\\%)' = NA,
		'\\hspace{10pt}Male' = ifelse(sex[1] == 'M' | sex[1] == 1, 1, 0),
		'\\hspace{10pt}Female' = ifelse(sex[1] == 'F' | sex[1] == 0, 1, 0),
		"\\textbf{Plant}$^\\natural$, $n$ (\\%)" = NA,
		"\\hspace{10pt}Plant 1" = as.numeric(names(sort(table(PLANT[cal_obs < 1995]), decreasing = T)[1])) == 1,
		"\\hspace{10pt}Plant 2" = as.numeric(names(sort(table(PLANT[cal_obs < 1995]), decreasing = T)[1])) == 2,
		"\\hspace{10pt}Plant 3" = as.numeric(names(sort(table(PLANT[cal_obs < 1995]), decreasing = T)[1])) == 3,
		'\\textbf{Complete work records}' = as.numeric(floor(get(yout.which)[1]) < 1995),
		
		# Years since follow-up
		'\\textbf{Year of hire}' = floor(YIN16[1]),
		'\\textbf{Age at hire}' = YIN16[1] - YOB[1],
		'\\textbf{Year of birth}' = floor(YOB[1]),
		'\\textbf{Year of worker exit}' = {
			if (get(yout.which)[1] != 1995) {
				get(yout.which)[1]
			} else {NaN}},
		'\\textbf{Age at worker exit}' = {
			if (get(yout.which)[1] != 1995) {
				get(yout.which)[1] - YOB[1]
			} else {NaN}},
		'\\textbf{Length of follow-up}' = min(2016, yod15[1]) - max(YIN16[1] + 3, 1941, start_year),
		'\\textbf{Age at death among deceased}' = if (yod15[1] < 2016) {
			yod15[1] - YOB[1]} else {NaN},
		'\\textbf{Year of death among deceased}' = if (yod15[1] < 2016) {
			floor(yod15[1])} else {NaN}
	),
	by = .(STUDYNO)][,-'STUDYNO']
	
	# Population-level summary
	table.break <- "Year of hire"
	tab1 <- rbind(
		t(apply(tab1.sum[,1:(grep(table.break, names(tab1.sum)) - 1)], 2, function(x) {
			return(
				c(mean(x, na.rm = T) * sum(!is.na(x)),
					mean(x, na.rm = T) * 100,
					NA
					# NA,
					# NA
				)
			)
		})),
		t(apply(tab1.sum[,grep(table.break, names(tab1.sum)):ncol(tab1.sum)], 2,
						function(x) {
							return(
								c(
									# mean(x, na.rm = T),
									# sd(x, na.rm = T)
									# min(x, na.rm = T),
									median(as.numeric(x), na.rm = T),
									quantile(as.numeric(x), 0.25, na.rm = T),
									quantile(as.numeric(x), 0.75, na.rm = T)
									# max(x, na.rm = T)
								)
							)
						}))
	)
	
	tab1[!is.finite(as.matrix(tab1))] <- NA
	
	# Table names
	colnames(tab1) <- c('n', '%', "tmp")#, 'Minimum', 'Median', 'Maximum')
	
	# Digits
	tab1.digits <- matrix(2, ncol = 3,#5
												nrow = nrow(tab1))
	tab1.digits[grep("Age", rownames(tab1), ignore.case = T), ] <- 0
	tab1.digits[grep("year ", rownames(tab1), ignore.case = T), ] <- 0
	tab1.digits[1:(grep(table.break, rownames(tab1), ignore.case = T) - 1), -1] <- 0
	
	tab1 <- matrix(
		sapply(1:length(tab1), function(i) {
			as.character(round(as.vector(tab1)[i], as.vector(tab1.digits)[i]))
		}),
		ncol = ncol(tab1),
		nrow = nrow(tab1),
		dimnames = dimnames(tab1)
	)
	
	# Pretty counts
	tab1[1:(grep(table.break, rownames(tab1)) - 1), 1] <- sapply(
		tab1[1:(grep(table.break, rownames(tab1)) - 1), 1],
		function (i) {
			if (!is.na(i)) {
				prettyNum(as.numeric(i), big.mark = ' ')
			} else {NA}
		})
	
	# Pretty percents
	tab1[1:(grep(table.break, rownames(tab1)) - 1), 2] <- sapply(
		tab1[1:(grep(table.break, rownames(tab1)) - 1), 2],
		function (i) {
			if (!is.na(i)) {
				paste0(as.numeric(i), '%')
			} else {NA}
		})
	
	# Quartiles one column
	tab1[!is.na(tab1[,3]),2] <- paste0(
		tab1[!is.na(tab1[,3]),2],
		", ",
		tab1[!is.na(tab1[,3]),3]
	)
	
	tab1 <- tab1[,-3]
	
	# Second column gets parentheses
	tab1[!is.na(tab1[,1]), 2] <- paste0(
		"(", tab1[!is.na(tab1[,1]), 2], ")"
	)
	
	# Math mode
		# tab1 <- matrix(
		# 	sapply(1:length(tab1), function(i) {
		# 		if (!is.na(as.vector(tab1)[i])) {
		# 			paste0('$', as.vector(tab1)[i], '$')
		# 		} else {NA}
		# 	}),
		# 	ncol = ncol(tab1),
		# 	nrow = nrow(tab1),
		# 	dimnames = dimnames(tab1))
	
	# Counts
	tab1 <- rbind(
		c(paste0(prettyNum(n_distinct(df$STUDYNO), big.mark = ' ')),
			paste0('(',
						 prettyNum(round(sum(df[,.(py = min(yod15[1], 2016, na.rm = T) - YIN16[1] - 3), by = .(STUDYNO)]$py), 0), big.mark = ' '),
						 ')')
		),
		tab1
	)
	rownames(tab1)[1] <- "$N$ (person$\\cdot$years)"
	
	tab1.rownames <- rownames(tab1)
	
	# # Collapse columns
	# tab1[!is.na(tab1[,1]), 1] <- paste(
	# 	tab1[!is.na(tab1[,1]), 1],
	# 	tab1[!is.na(tab1[,1]), 2]
	# )
	# tab1 <- tab1[,-2]
	
	tab1 <- as.data.frame(tab1)
	
	rownames(tab1) <- tab1.rownames
	colnames(tab1) <- c(col.name, " ")
	
	if (table_engine != "xtable") {
		rownames(tab1) <- gsub("\\\\hspace\\{10pt\\}", "&nbsp;&nbsp;&nbsp;&nbsp;", rownames(tab1))
		rownames(tab1) <- gsub("\\\\textbf\\{", "**", rownames(tab1))
		rownames(tab1) <- gsub("\\}", "**", rownames(tab1))
	}
	
	detach(package:data.table)
	detach(package:lubridate)
	
	return(tab1)
}

# Get Table 2 for full ANALYTIC cohort
all.tab2 <- get.tab1(df = filter(dta_ips, filler == 0), col.name = "Analytic cohort", start_year = 1970, table_engine = "pander")
# For suicide cases in the ANALYTIC cohort
suicide.tab2 <- get.tab1(df = filter(dta_ips, suicide == 1, filler == 0), col.name = "Suicide cases", start_year = 1970, table_engine = "pander")
# For overdose cases in the ANALYTIC cohort
poison.tab2 <- get.tab1(df = filter(dta_ips, poison == 1, filler == 0), col.name = "Fatal overdose cases", start_year = 1970, table_engine = "pander")

tab2 <- cbind(all.tab2, suicide.tab2, poison.tab2)

# Get Table 1 for full FULL cohort
all.tab1 <- get.tab1(df = cohort_long, col.name = "Full cohort", table_engine = "pander")
# For suicide cases in the FULL cohort
suicide.tab1 <- get.tab1(df = filter(cohort_long, suicide == 1), col.name = "Suicide cases", table_engine = "pander")
# For overdose cases in the FULL cohort
poison.tab1 <- get.tab1(df = filter(cohort_long, poison == 1), col.name = "Fatal overdose cases", table_engine = "pander")

tab1 <- cbind(all.tab1, suicide.tab1, poison.tab1)

# # Print to TeX
# connection <- file(here::here("reports", "table2.tex"))
# writeLines(print.xtable(xtable(tab1), sanitize.text.function = function(x) {x}), connection)
# close(connection)
# 
# connection <- file(here::here("reports", "table1.tex"))
# writeLines(print.xtable(xtable(full.tab1), sanitize.text.function = function(x) {x}), connection)
# close(connection)
```

```{r tab1}
rownames(tab1) <- gsub("\\\\hspace\\{10pt\\}", "&nbsp;&nbsp;&nbsp;&nbsp;", rownames(tab1))
rownames(tab1) <- gsub("\\\\textbf\\{", "**", rownames(tab1))
rownames(tab1) <- gsub("\\}", "**", rownames(tab1))
pander(tab1, emphasize.rownames = F, missing = "", justify = c("lrlrlrl"),
			 caption = "Characteristics of the overall cohort, suicide cases, and overdose cases, UAW-GM cohort 1941-2015.")
```


```{r tab2}
rownames(tab2) <- gsub("\\\\hspace\\{10pt\\}", "&nbsp;&nbsp;&nbsp;&nbsp;", rownames(tab2))
rownames(tab2) <- gsub("\\\\textbf\\{", "**", rownames(tab2))
rownames(tab2) <- gsub("\\}", "**", rownames(tab2))
pander(tab2, emphasize.rownames = F, missing = "", justify = c("lrlrlrl"),
			 caption = "Characteristics of the IPS overall cohort, suicide cases, and overdose cases, UAW-GM cohort 1970-2015.")
```